In [1]:
#understanding the kernals /filters /windows

In [2]:
import numpy as np

kernal = np.ones((3,3), dtype = int)
print(kernal)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [1]:
import cv2
import numpy as np

#Load the image
img = cv2.imread('saltandpepper1.png',1)

kernal = np.ones((5,5) , np.float32)/25

dst = cv2.filter2D(img,-1,kernal)#src , depth,kernel

result = np.hstack((img,dst))

cv2.imshow('result',result)
cv2.waitKey(0)

-1

In [2]:
#4.Application of imaage blurring

In [ ]:
import cv2
import numpy as np

#load the iamge


#Create a custome kernal of size 15x15 and apply to the input image


#Apply threshholding operator to highlight the largest object


result = np.hstack((img,dst,thresh)
cv2.imshow('result',result)
cv2.waitKey(0)                 
                   